### ISSUE TITLE
add suport for Square Covers

### ISSUE THREAD

**Issue by Dr4goonDemon** [cooperate/SteamGridDBMetadata#16]
Please add support for 1024x1024 and 512x512 covers that will help very much in the case of using full screen themes like the Ish variants (xboxseriesish, ps5ish)

**Comment by darklinkpower** [comment]
This got added https://github.com/cooperate/SteamGridDBMetadata/commit/29a6a595d79f875a581e84273787defc372994fb and is available in the current release.
