### ISSUE TITLE
Extension "SteamGridDB Metadata Provider" failed to load properly.

### ISSUE THREAD

**Issue by ghost** [cooperate/SteamGridDBMetadata#21]
Greetings,

![SteamGridDB](https://user-images.githubusercontent.com/92376844/136958906-115f9f62-5c9d-4af4-9979-db64591ba4dc.png)

This is happening with completely clean instance of Playnite 8.15. I don't have any additional extension or anything like that.

Since the plugin failed to load, I was not able to set API key and so on.

**Comment by LerainLawliet** [comment]
My bad - I was using "SteamGridDB_Playnite_Metadata_1_0.pext" (the latest one that has Playnite 9 beta support) on a Playnite 8.15

I thought they are backward compatible. The old version (SteamGridDB_Metadata_Provider_0_5_12.pext) works well.
