### ISSUE TITLE
Failed to download metadata: Service failure during getHeroImages

### ISSUE THREAD

**Issue by azumukupoe** [cooperate/SteamGridDBMetadata#24]
![image](https://user-images.githubusercontent.com/31339007/141613126-528f7717-fc12-49e4-839f-af6fc5dd0df8.png)

**Comment by ccrowles** [comment]
Same issue for certain games, but for "GetLogoImages".

![image](https://user-images.githubusercontent.com/12866474/150554308-42556afd-84a1-44b9-816e-63c8b80781f0.png)

**Comment by Fennecai** [comment]
same issue here but with the icons. seems to happen with games that were added recently to steamgriddb or something...
![image](https://user-images.githubusercontent.com/10889213/156301761-d25d0c44-6417-4cfe-beab-32fbc44c988f.png)

**Comment by doZennn** [comment]
> I have the same error. I have attached a copy of the log here Extension log: https://pastebin.pl/view/8e308504
> 
> Playnite log: https://pastebin.pl/view/0c852c1a

Looks like the `styles` param is being added to the wrong asset type. Heroes don't have a "no_logo" style.

**Comment by raygan** [comment]
I've been having this same issue (Service failure during getHeroImages) since around when Playnite 9 came out. For me it's every game, not just certain ones. It's definitely downloading something, since it will usually ask me to choose between icon or cover options, but when it gets to hero images it fails and doesn't save. I'm not sure how to share a log from this but happy to do so if someone doesn't mind telling me where they're located.

**Comment by chefreinhold** [comment]
> inc

I installed this add-on. It adds an open log option to the main menu:
https://playnite.link/forum/thread-535.html
https://github.com/darklinkpower/PlayniteExtensionsCollection

**Comment by chefreinhold** [comment]
> I've been having this same issue (Service failure during getHeroImages) since around when Playnite 9 came out. For me it's every game, not just certain ones. It's definitely downloading something, since it will usually ask me to choose between icon or cover options, but when it gets to hero images it fails and doesn't save. I'm not sure how to share a log from this but happy to do so if someone doesn't mind telling me where they're located.

I installed this add-on. It adds an open log option to the main menu:
https://playnite.link/forum/thread-535.html
https://github.com/darklinkpower/PlayniteExtensionsCollection

**Comment by raygan** [comment]
Thanks, I think this is the relevant portion of the log:

`08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:getHeroImages
08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:FutureGrind
08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:
08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:356260
08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:getSGDBGameHero
08-03 15:48:12.173|INFO |SGDBMetadata#SgdbServiceClient:https://www.steamgriddb.com/api/v2/heroes/game/6975?styles=no_logo&nsfw=false&humor=false
08-03 15:48:12.243|INFO |SGDBMetadata#SgdbServiceClient:{"success":false,"errors":["Invalid style"]}`

https://pastebin.com/GvpyhVfU

**Comment by darklinkpower** [comment]
Fixed in f49dd21320bd54fddc523823d9c76c719b7e4251
