### ISSUE TITLE
Don't show game selection for all media types when downloading manually

### ISSUE THREAD

**Issue by JosefNemec** [cooperate/SteamGridDBMetadata#3]
When downloading metadata manually while editing the game, plugin asks for game selection before each and every media type:

`select game -> select icon -> select game -> select cover -> select game -> select background`

It IMHO doesn't make sense to ask for game selection for each media type, since all media types are available under one game record on steamgriddb, asking only once would make much more sense:

`select game -> select icon -> select cover ->  -> select background`

**Comment by darklinkpower** [comment]
@cooperate told me that it was intended (But I didn't understand why). If needed, another option is to perhaps make this behaviour configurable because only in very rare situations you'll want to grab metadata from 2 different games.

**Comment by cooperate** [comment]
Addressed this in v0.5.  Please test!

**Comment by darklinkpower** [comment]
It's working great, not asking multiple times to select the game anymore.
