### ISSUE TITLE
"Object reference not set to an instance of an object" error when canceling dialogue or closing

### ISSUE THREAD

**Issue by darklinkpower** [cooperate/SteamGridDBMetadata#5]
Tested with version 0.5

Happens when closing the window or canceling in the game selection window

![imagen](https://user-images.githubusercontent.com/1389286/83176814-b43ae380-a0e3-11ea-99a5-06befb5c7523.png)

![imagen](https://user-images.githubusercontent.com/1389286/83176862-c7e64a00-a0e3-11ea-8362-068ed80ca13e.png)

**Comment by cooperate** [comment]
@darklinkpower Should be resolved now in my latest hotfix release.  If you find any problems let me know. Thanks!

**Comment by darklinkpower** [comment]
Thanks! can confirm the issue is gone.
