### ISSUE TITLE
Steam Grid DB Metadata" not appearing under "Metadata sources" in Playnite

### ISSUE THREAD

**Issue by sengtsan** [cooperate/SteamGridDBMetadata#7]
I installed the plugin and have activated it but cannot see "Steam Grid DB Metadata" under "Metadata sources"... 

I am using Playnite version 7.9.

![image](https://user-images.githubusercontent.com/63714826/95604211-3f8f9280-0a4f-11eb-85ad-5a9fb8dd4567.png)

**Comment by cooperate** [comment]
I'll test this with the latest update thanks.

**Comment by cooperate** [comment]
Could not replicate on my side.  Ensure you have the latest version (0.5.5) and are running the latest version of Playnite (8.0 atm)

@sengtsan

**Comment by sengtsan** [comment]
Ah! Updating to the latest versions of both did it. 
Thank you, appreciate it
