### ISSUE TITLE
Extension can't be installed in Playnite 8

### ISSUE THREAD

**Issue by darklinkpower** [cooperate/SteamGridDBMetadata#9]
Playnite 8 requires an `Id` property in extension manifests or will refuse to install

https://playnite.link/docs/playnite8/changelog.html
https://playnite.link/docs/playnite8/tutorials/extensionsManifest.html

![imagen](https://user-images.githubusercontent.com/1389286/96120923-e7281d00-0eb4-11eb-9a25-11796d1bff47.png)

**Comment by shakeyourbunny** [comment]
would really like to see this updated.

**Comment by cooperate** [comment]
Should be corrected now on 0.5.5, test and verify.

**Comment by awbooze** [comment]
I just downloaded the extension and installed it on Playnite 8.1, so it works on my machine. Thanks for the update!

**Comment by darklinkpower** [comment]
Installed and confirmed working, thanks. I'll go ahead and close the issue.
